services:
  mongo:
    image: mongo:8
    container_name: eventos-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: mongod --quiet --logpath /dev/null
    restart: always
  # api:
  #    container_name: eventos-api
  #    build: .
  #    ports:
  #      - "${API_PORT}:${API_PORT}"
  #    env_file:
  #      - ./.env
  #    environment:
  #     - NODE_ENV=development
  #     - DB_URL=mongodb://eventos-mongodb:27017/ifro_eventos
  #     - API_PORT=5015
  #     - SWAGGER_DEV_URL=http://localhost:5015

  #    depends_on:
  #      - mongo
  # mailsender:
  #   image: ruanlopes1350/mailsender:latest
  #   ports:
  #     - "5016:5016"
  #   env_file:
  #     - .env.mailsender
  #   restart: always
  #   depends_on:
  #     - api

  # frontend:
  #   container_name: eventos-front
  #   build:
  #     context: ../frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - ../frontend/.env.local
  #   environment:
  #     - NEXT_PUBLIC_API_URL=http://iplocal:5015
  #     - API_URL_SERVER_SIDED=http://api:5015
  #   restart: always
  #   depends_on:
  #     - api

volumes:
  mongo-data:
