services:
  mongo:
    image: mongo:8
    container_name: eventos-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: mongod --quiet --logpath /dev/null
    restart: always
    networks:
      - mynet

  # minio:
  #   image: minio/minio:latest
  #   container_name: minio
  #   environment:
  #     - MINIO_ROOT_USER=admin
  #     - MINIO_ROOT_PASSWORD=admin1234
  #   volumes:
  #     - minio_data:/data
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   command: server /data --console-address ":9001"
  #   restart: always
  #   networks:
  #     - mynet

  # api:
  #   container_name: eventos-api
  #   build: .
  #   ports:
  #     - "${API_PORT:-5015}:${API_PORT:-5015}"
  #   env_file:
  #     - ./.env
  #   environment:
  #     - NODE_ENV=development
  #     - DB_URL=mongodb://eventos-mongodb:27017/ifro_eventos
  #   restart: always
  #   depends_on:
  #     - mongo
  #     - minio
  #   networks:
  #     - mynet

  # frontend:
  #   container_name: eventos-front
  #   build:
  #     context: ../frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - ../frontend/.env.local
  #   environment:
  #     - NEXT_PUBLIC_API_URL=http://localhost:5015
  #     - API_URL_SERVER_SIDED=http://api:5015
  #   restart: always
  #   depends_on:
  #     - api
  #   networks:
  #     - mynet
networks:
  mynet:
    driver: bridge
volumes:
  mongo-data:
  minio_data:
    driver: local
